import { type Course } from '@/types/Course.types';

export const COURSES: Course[] = [
  {
    id: 'webtech',
    title: 'Web Technology',
    path: 'WebTech',
    color: 'oklch(0.75 0.18 45)',
    cssVar: '--color-webtech',
    icon: 'globe',
    description: 'HTML, CSS & JavaScript fundamentals',
    subcourses: ['HTML', 'CSS', 'JS'],
  },
  {
    id: 'sql',
    title: 'SQL',
    path: 'SQL',
    color: 'oklch(0.65 0.18 220)',
    cssVar: '--color-sql',
    icon: 'database',
    description: 'Database queries, scripts and schema design',
  },
  {
    id: 'java',
    title: 'Java',
    path: 'Java',
    color: 'oklch(0.65 0.20 20)',
    cssVar: '--color-java',
    icon: 'coffee',
    description: 'Core Java programming concepts',
  },
  {
    id: 'advanced-java',
    title: 'Advanced Java',
    path: 'AdvancedJava',
    color: 'oklch(0.60 0.20 310)',
    cssVar: '--color-advanced-java',
    icon: 'zap',
    description: 'Servlets, JSP, JDBC and more',
  },
  {
    id: 'hibernate',
    title: 'Hibernate',
    path: 'Hibernate',
    color: 'oklch(0.60 0.15 55)',
    cssVar: '--color-hibernate',
    icon: 'layers',
    description: 'ORM framework with Hibernate',
  },
  {
    id: 'springboot',
    title: 'Spring Boot',
    path: 'SpringBoot',
    color: 'oklch(0.70 0.20 145)',
    cssVar: '--color-springboot',
    icon: 'leaf',
    description: 'REST APIs and backend with Spring Boot',
  },
  {
    id: 'reactjs',
    title: 'React JS',
    path: 'ReactJS',
    color: 'oklch(0.72 0.18 200)',
    cssVar: '--color-react',
    icon: 'atom',
    description: 'Modern frontend with React',
  },
  {
    id: 'python',
    title: 'Python',
    path: 'Python',
    color: 'oklch(0.80 0.18 95)',
    cssVar: '--color-python',
    icon: 'terminal',
    description: 'Python scripting and programming',
  },
];

export const COURSE_MAP = Object.fromEntries(COURSES.map((c) => [c.id, c]));
